version: '3.9'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    ports:
      - '5432:5432'
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - my_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9090:9090'
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ['/app/wait-for.sh', 'postgres:5432', '--', '/app/start.sh']
    command: ['/app/main']
    networks:
      - my_network

volumes:
  pgadmin_data:

networks:
  my_network:
    driver: bridge
